// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqcovsorraqpovgzugzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxY292c29ycmFxcG92Z3p1Z3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDczMjQsImV4cCI6MjA3MjcyMzMyNH0.aLU4KWREgNyi8f6l_VFap6wN_0R7-0dbDFlUV-i1S7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});